# This is a basic workflow to help you get started with Actions

name: Updating Github Metrics

# Controls when the action will run.
on:
  schedule:
    - cron: "0 */8 * * *"
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  metrics:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # See https://github.com/lowlighter/metrics for documentation
      - name: 🦑 Personal metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Asia/Shanghai

          base: header, repositories
          repositories: 100
          repositories_affiliations: owner, collaborator, organization_member
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_topics: yes
          plugin_topics_mode: starred
          commits_authoring: ${{ secrets.AUTHOR_EMAILS }}
          config_order: base.header, base.repositories, isocalendar, notable, topics

      # ======================================================================================
      # 🈷️ Indepth languages stats
      - name: 🈷️ Languages plugin (most used)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.languages.most.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: qqsuhao/qqsuhao
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
          commits_authoring: ${{ secrets.AUTHOR_EMAILS }}

      # 🈷️ Indepth languages stats
      - name: 🈷️ Languages plugin (recently used)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.languages.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: qqsuhao/qqsuhao
          plugin_languages_indepth: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 600
          plugin_languages_recent_days: 180
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
          commits_authoring: ${{ secrets.AUTHOR_EMAILS }}

      # 🧮 Repositories traffic
      # Display number of repositories views (this is part of base content "repositories" section, so you need to enable it)
      # Note that a "repo" scope is required
      - name: 🧮 Traffic plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_traffic: yes

      # 📌 Starred topics
      # Display starred topics (as labels)
      - name: 📌 Topics plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
